export { HomeIcon } from './HomeIcon';
export { ProfileIcon } from './ProfileIcon';
export { HeartIcon } from './HeartIcon';
export { CartIcon } from './CartIcon';
export { SearchIcon } from './SearchIcon';
export { BackArrowIcon } from './BackArrowIcon';
export { FireIcon } from './FireIcon';
export { PercentIcon } from './PercentIcon';
export { BestIcon } from './BestIcon';
export { LanguageIcon } from './LanguageIcon';
export { MenuIcon } from './MenuIcon';
export { CloseIcon } from './CloseIcon';
export { TelegramIcon } from './TelegramIcon'
export { InstagramIcon } from './InstagramIcon'
export { TikTokIcon } from './TikTokIcon'
export { PhoneIcon } from './PhoneIcon'